swipe:
  3:
    left:
      command: "xdotool key alt+Right" # History forward 
    right:
      command: "xdotool key alt+Left" # History back
  4:
    left:
      command: "xdotool key ctrl+alt+Right" # Switch to next workspace
    right:
      command: "xdotool key ctrl+alt+Left" # Switch to previous workspace
    up:
      command: "xdotool key ctrl+F10" # Show all applications
    down:
      command: "xdotool key ctrl+F12" # Show desktop
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out

